location: westus
resourceGroup: ladder-league-rg
properties:
  environmentId: /subscriptions/{subscription-id}/resourceGroups/ladder-league-rg/providers/Microsoft.App/managedEnvironments/ladder-league-env
  configuration:
    ingress:
      external: true
      targetPort: 8000
      allowInsecure: false
    registries:
    - server: ladderleagueregistry.azurecr.io
      username: ladderleagueregistry
  template:
    containers:
    - name: ladder-league-api
      image: ladderleagueregistry.azurecr.io/ladder-league-api:latest      env:
      - name: LADDER_LEAGUE_DATA_DIR
        value: /mnt/data
      volumeMounts:
      - volumeName: data-volume
        mountPath: /mnt/data
    scale:
      minReplicas: 1
      maxReplicas: 3
    volumes:
    - name: data-volume
      storageType: AzureFile
      storageName: ladder-data-storage
